### ISSUE TITLE
Failed config in ESPHome 2023.12.9

### ISSUE THREAD

**Issue by tv4you2016** [sehraf/esphome-components#2]
INFO ESPHome 2023.12.9
INFO Reading configuration esp32-audiokit-voice-assistant.yaml...
INFO Updating https://github.com/sehraf/esphome-components@main
Failed config

media_player.i2s_audio: [source <unicode string>:123]
  platform: i2s_audio
  id: media_out
  name: Media Player
  dac_type: external
  i2s_dout_pin: 25

  [allow_other_uses] is an invalid option for [media_player.i2s_audio]. Please check the indentation.
  allow_other_uses: True
  mode: stereo
speaker.i2s_audio: [source <unicode string>:136]
  platform: i2s_audio
  id: speaker_out
  dac_type: external
  i2s_dout_pin: 25

  [allow_other_uses] is an invalid option for [speaker.i2s_audio]. Please check the indentation.
  allow_other_uses: True
  mode: stereo

**Comment by sehraf** [comment]
I've updated the config, your pins should look like, for example, this:
https://github.com/sehraf/esphome-components/blob/17c6734098da4fbac2b2b966d1b2b8707b4abc77/esp32-audiokit-voice-assistant.yaml#L148-L150

This properly validates here.
